spring:
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 161092
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: user-events
    consumer:
      group-id: notification-group

